name: Update GeoJSON

on:
  schedule:
    - cron: '30 00  * * * '  # Ejecuta cada hora
  workflow_dispatch:  # Permite ejecución manual desde la interfaz de GitHub

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          pip install requests

      - name: Fetch Predictions Data from Airtable and Generate data.geojson
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python generate_geojson.py

      - name: Fetch Module Data from Airtable and Generate modules.geojson
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python generate_modules.py

      - name: Fetch Settlements Data from Airtable and Generate settlements.geojson
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python generate_settlements.py

      - name: Fetch Modules and Clients Data from Airtable and Generate filtered_modules.geojson
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python client_modules.py

      - name: Commit and Push Changes (if needed)
        run: |
          git config user.name "GitHub Bot"
          git config user.email "bot@github.com"
          git add data.geojson modules.geojson settlements.geojson filtered_modules.geojson
          git diff --cached --exit-code || git commit -m "Auto-update GeoJSON files from Airtable"
          git push origin main
